version: '3.1'

services:

  mysql:
    platform: linux/amd64
    image: mysql:8.0.26
    restart: always
    ports:
      - "3308:3306"
    # volumes:
    #   - ./my-datavolume:/var/lib/mysql
    env_file: .env


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080